import jax
import jax.numpy as jnp
from typing import Any, Dict, List, Optional, Tuple
from dataclasses import dataclass, field

from fabricpc.core.inference import run_inference


@dataclass
class GenerativeReplayBuffer:
    """Buffer of (input, target) pairs generated by the PC network itself.

    Instead of storing real data, the PC graph generates pseudo-samples after
    learning a task.  These are replayed when learning the next task to
    maintain performance on earlier tasks.

    The buffer is bounded by `max_size`; when full, the oldest task's samples
    are evicted first (proportional to task count).
    """

    max_size: int
    _data: Dict[str, Tuple[jnp.ndarray, jnp.ndarray]] = field(default_factory=dict)

    def __len__(self) -> int:
        return sum(x.shape[0] for x, _ in self._data.values())

    def update_from_model(
        self,
        params: Any,
        structure: Any,
        task_identifier: str,
        rng_key: jax.Array,
        n_samples: int = 200,
    ) -> None:
        """Generate replay samples from the PC graph for this task.

        The graph's output node is unclamped and free-running; the converged
        latent at the output is treated as a pseudo-target.  The input is
        sampled from the graph's input node distribution (zero-centred noise
        propagated through the clamped input node).
        """
        from fabricpc.graph_initialization.state_initializer import (
            initialize_graph_state,
        )

        y_node = structure.task_map.get("y")
        x_node = structure.task_map.get("x")
        if y_node is None or x_node is None:
            return

        x_shape = structure.nodes[x_node].node_info.shape
        batch_shape = (n_samples,) + x_shape

        keys = jax.random.split(rng_key, 3)
        noise = jax.random.normal(keys[0], batch_shape) * 0.5

        clamps = {x_node: noise}

        init_state = initialize_graph_state(
            structure, n_samples, keys[1],
            clamps=clamps, params=params,
        )
        final_state = run_inference(params, init_state, clamps, structure)

        pseudo_y = final_state.nodes[y_node].z_latent
        pseudo_x = noise

        new_samples = (pseudo_x, pseudo_y)
        self._data[task_identifier] = new_samples

        total = self.__len__()
        if total > self.max_size:
            keys_to_evict = sorted(self._data.keys())[:-1]
            for k in keys_to_evict:
                del self._data[k]

    def sample(
        self,
        n: int,
        rng_key: jax.Array,
    ) -> Optional[Tuple[jnp.ndarray, jnp.ndarray]]:
        """Uniformly sample replay pairs across all stored tasks."""
        if not self._data:
            return None

        all_x, all_y = [], []
        for x, y in self._data.values():
            all_x.append(x)
            all_y.append(y)

        xs = jnp.concatenate(all_x, axis=0)
        ys = jnp.concatenate(all_y, axis=0)

        total = xs.shape[0]
        n_actual = min(n, total)
        idx = jax.random.randint(rng_key, (n_actual,), 0, total)

        return xs[idx], ys[idx]
